// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zqogndovdddajzeaflgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxb2duZG92ZGRkYWp6ZWFmbGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NTk2NTcsImV4cCI6MjA5MDEzNTY1N30.YImkKrRh9_NZT-p1SHj_SgwNbz1lFoOaLGEpFA_p8Xo";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);